---
ckan_virtualenv_path: "/usr/lib/ckan/default/"
ckanext_spatial_version: "da2e1100ed9600b0b8b2ceffbadc4f966e71274f"
ckan_config_path: "/etc/ckan/default/production.ini"
ckanext_spatial_url: "https://stamen-tiles.a.ssl.fastly.net/terrain/{z}/{x}/{y}.jpg"
ckanext_spatial_attribution: 'Map tiles by <a href="http://stamen.com">Stamen Design</a>, under <a href="http://creativecommons.org/licenses/by/3.0">CC BY 3.0</a>. Data by <a href="http://openstreetmap.org">OpenStreetMap</a>, under <a href="http://creativecommons.org/licenses/by-sa/3.0">CC BY SA</a>.'
