# Adapted from https://gist.github.com/jeffbr13/08751e42c9355cc44f5d
---
  - name: Upgrade all safe packages
    apt: upgrade=safe

  - name: Install unattended upgrades (Debian/Ubuntu only)
    apt: pkg=unattended-upgrades state=installed
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - name: 'Make sure unattended-upgrades only installs from $ubuntu_release-security'
    lineinfile: 'dest=/etc/apt/apt.conf.d/50unattended-upgrades regexp="$ubuntu_release-updates" state=absent'
    when: ansible_distribution == 'Ubuntu'

  - name: Install necessities and nice-to-haves
    apt: pkg={{ item }} state=installed
    with_items:
      - acl
      - apache2
      - apt-transport-https
      - apticron
      - aptitude
      - build-essential
      - debian-goodies
      - fail2ban
      - git
      - htop
      - iftop
      - iotop
      - libapache2-mod-wsgi
      - libffi-dev
      - libssl-dev
      - libpq5
      - nginx
      - postgresql
      - python
      - python-pip
      - python-psycopg2
      - python-pycurl
      - python-software-properties
      - python-dev
      - screen
      - solr-jetty
      - sudo
      - update-notifier-common
      - wget
    when: ansible_pkg_mgr == 'apt'

#    - name: Enable passwordless sudo
#      lineinfile: 'dest=/etc/sudoers regexp="sudo ALL=NOPASSWD: ALL" line="%sudo ALL=NOPASSWD: ALL" state=present'

  - name: Download CKAN package
    get_url: 'url="http://packaging.ckan.org/{{ ckan_package_filename }}" dest={{ ckan_package_dir }}/{{ ckan_package_filename }}'

  - name:  Install CKAN package
    command: 'dpkg --skip-same-version -i {{ ckan_package_dir }}/{{ ckan_package_filename }}'
    # http://stackoverflow.com/questions/19127493/in-ansible-how-do-you-prevent-a-dpkg-installation-task-to-notify-a-changed-stat
    register: ckan_installed
    changed_when: "'already installed' not in ckan_installed.stderr"
    notify:
      - Restart Apache
      - Restart Nginx

  - name: Ensure CKAN storage folders exist and that Apache can write to them
    file: path={{ item }} owner=www-data mode=0755 state=directory
    with_items:
        - /var/lib/ckan/default/storage
        - /var/lib/ckan/default/storage/uploads

  - name: Create pip.conf in virtualenv to suppress version warning
    template: src=pip.conf.j2
              dest={{ ckan_virtualenv_path }}/pip.conf
              mode="0755"

  - name: Install pip packages not covered by dependencies
    pip: name={{ item.name }} version={{ item.version }} virtualenv={{ ckan_virtualenv_path }}
    with_items: "{{ ckan_pip_dependencies }}"

  # Jetty & Solr
  - name: Set Jetty to start on boot
    lineinfile: 'dest=/etc/default/jetty regexp=^NO_START line="NO_START=0"'

  - name: Set Jetty host to localhost
    lineinfile: 'dest=/etc/default/jetty regexp=^JETTY_HOST line="JETTY_HOST=127.0.0.1"'

  - name: Set Jetty to port 8983
    lineinfile: 'dest=/etc/default/jetty regexp=^JETTY_PORT line="JETTY_PORT=8983"'

  - name: Set Jetty to use system java
    lineinfile: 'dest=/etc/default/jetty regexp=JAVA_HOME line="JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64/"'
    notify: Start Jetty

  - name: Remove CKAN schema file
    file: path=/etc/solr/conf/schema.xml state=absent
    when: ckan_installed.changed

  - name: Ensure CKAN uses provided schema file
    file: path=/etc/solr/conf/schema.xml src=/usr/lib/ckan/default/src/ckan/ckan/config/solr/schema.xml state=link
    notify: Restart Jetty

  - name: Set CKAN Solr server address
    lineinfile: 'dest={{ ckan_config_path }} regexp=solr_url line=solr_url=http://127.0.0.1:8983/solr'

  # Postgres
  - name: Ensure CKAN database is created
    postgresql_db: 'name={{ db_name }}'
    become_user: postgres
    when: db_host == 'localhost'

  - name: Ensure CKAN database user can access CKAN database
    postgresql_user: 'db={{ db_name }} name={{ db_user }} password={{ db_password }} priv=ALL'
    become_user: postgres
    when: db_host == 'localhost'

  - name: Minimise CKAN database user privileges
    postgresql_user: 'name={{ db_user }} role_attr_flags=NOSUPERUSER,NOCREATEROLE,NOCREATEDB'
    become_user: postgres
    when: db_host == 'localhost'

  - name: Set CKAN database server address
    lineinfile: 'dest={{ ckan_config_path }} regexp=sqlalchemy.url line="sqlalchemy.url = postgresql://{{ db_user }}:{{ db_password }}@{{ db_host }}/{{ db_name }}?sslmode=disable"'

  - name: Ensure database is initialised
    command: ckan db init
    when: db_host == 'localhost'
    notify:
      - Restart Apache
      - Restart Nginx

  - name: Remove Repoze.who configuration file for CKAN
    file: path=/usr/lib/ckan/default/src/ckan/who.ini state=absent
    when: ckan_installed.changed

  - name: Link Repoze.who configuration file for CKAN
    file: 'path=/usr/lib/ckan/default/src/ckan/who.ini src=/etc/ckan/default/who.ini state=link'

# DataStore
  - name: Ensure DataStore database exists
    postgresql_db: name=datastore_default owner=ckan_default
    become_user: postgres
    when: db_host == 'localhost'

  - name: Ensure CKAN database user owns DataStore database
    postgresql_user: 'db=datastore_default name=ckan_default password={{ db_password }} priv=ALL'
    become_user: postgres
    when: db_host == 'localhost'

  - name: Ensure DataStore database user exists
    postgresql_user: 'name=datastore_default password={{ db_password }}'
    become_user: postgres
    when: db_host == 'localhost'

  - name: Set DataStore database server write address
    lineinfile: 'dest={{ ckan_config_path }} regexp="ckan.datastore.write_url" line="ckan.datastore.write_url = postgresql://ckan_default:{{ db_password }}@{{ db_host }}/datastore_default"'

  - name: Set DataStore database server read address
    lineinfile: 'dest={{ ckan_config_path }} regexp="ckan.datastore.read_url" line="ckan.datastore.read_url = postgresql://datastore_default:{{ db_password }}@{{ db_host }}/datastore_default"'

  - name: Set DataStore database permissions
    command: ckan datastore set-permissions postgres
    when: db_host == 'localhost'


  # FileStore
  - name: Ensure FileStore directory exists
    file: path=/var/lib/ckan/default owner=www-data state=directory

  - name: Set FileStore directory path
    lineinfile: 'dest={{ ckan_config_path }} regexp="ckan.storage_path" line="ckan.storage_path = /var/lib/ckan/default"'

  - name: Ensure Apache can write to FileStore directory
    acl: name=/var/lib/ckan/default entity=www-data etype=user permissions=u+rwx
    notify: Restart Apache

  # Simple plugins
  - name: Install simple plugins into ckan virtualenv
    pip:
      name: "git+https://github.com/{{ item.repo }}.git@{{ item.version }}#egg={{ item.name }}"
      virtualenv: "{{ ckan_virtualenv_path }}"
    with_items: "{{ ckan_simple_plugins }}"

  - name: Add simple plugins to CKAN plugin list
    lineinfile: dest="{{ ckan_config_path }}" regexp="^ckan.plugins(((?!{{ item.1 }}).)*)$" line="ckan.plugins\1 {{item.1 }}" backrefs=yes
    notify: Restart Apache
    with_subelements:
      - "{{ ckan_simple_plugins }}"
      - plugins
