---
- hosts: vagrant

  become: True

  pre_tasks:
    - name: Update APT cache
      apt: update_cache=yes

  roles:
    - { role: "ckan.app" }
    # - { role: "ckanext-spatial" }
    - { role: "ckanext-datajson" }
    - { role: "ckanext-odp_theme" }
    # - { role: "ckanext-googleanalytics" }
    - { role: "ckan-odp-configuration" }
