---
- hosts: staging
  sudo: True
  roles:
    - { role: "ckan" }
    - { role: "ckanext-archiver" }
    - { role: "ckanext-qa" }
    - { role: "ckanext-disqus" }
    - { role: "ckanext-issues" }
    - { role: "ckanext-geoview" }
    - { role: "ckanext-deadoralive" }
    - { role: "ckanext-datajson" }
    - { role: "ckan-deadoralive" }
    - { role: "ckanext-odp_theme" }
    - { role: "ckanext-pages" }
    - { role: "ckanext-googleanalytics" }
    - { role: "ckan-odp-configuration" }
